# Generated by Django 3.2.18 on 2023-05-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('low_age_percentage', models.IntegerField(blank=True, null=True)),
                ('high_age_percentage', models.IntegerField(blank=True, null=True)),
                ('gender_percentage', models.IntegerField(blank=True, null=True)),
                ('wanted_percentage', models.IntegerField(blank=True, null=True)),
                ('low_age_check', models.BooleanField(default=False)),
                ('high_age_check', models.BooleanField(default=False)),
                ('gender_check', models.BooleanField(default=False)),
                ('created_at', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('flag', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Notselected', 'notselected')], default='Notselected', max_length=20)),
                ('accountaddress', models.CharField(blank=True, default='', max_length=200)),
                ('age_low', models.IntegerField(blank=True, null=True)),
                ('age_high', models.IntegerField(blank=True, null=True)),
                ('tweet_count', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('Ok', 'ok'), ('Not okay', 'not okay')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('labeled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, default=0, null=True)),
                ('processfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labeling.process')),
            ],
        ),
    ]
