# Generated by Django 3.2.16 on 2022-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='max_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='succces_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
