# Generated by Django 3.2.18 on 2023-05-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20221116_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='reviewed_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='succces_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotAcceptedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountaddress', models.CharField(blank=True, default='', max_length=200)),
                ('accountid', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.process')),
            ],
        ),
    ]
