# Generated by Django 3.2.15 on 2022-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulldetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
