# Generated by Django 3.2.16 on 2022-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulldetail', '0002_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='repeated_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='success_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='twtcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
